name: Package creator

on: [pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print build software versions
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cmake --version
        make --version

    - name: Build Project
      shell: bash
      working-directory: ${{github.workspace}}
      run: ./scripts/build.sh
